### ISSUE TITLE
Issues with fn_assignGear file with more than one faction being present in the database.

### ISSUE THREAD

**Issue by matthewbetts96** [matthewbetts96/A3GearScriptGenerator#1]
Currently, the fn_assignGear file is generated by collecting all possible factions that exist within the database and writing the appropriate lines to the file. However, because it writes the '#include' statement Arma must have those files when the mission is loaded or it crashes. Which is not good. Try-catch and other loading methods have proved unsuccessful.

**Comment by Poulern** [comment]
We could always use execvm instead, however it will still throw an error in everyone's face(and might not load the mission still). 

Solution is really just not generate all factions in fn_assigngear, and make people manually merge them(its not ideal, but its not possible to work around halfway executing code in arma 3 it seems)
