### ISSUE TITLE
Horrible typo Independant instead of Independent and other clarity suggestions

### ISSUE THREAD

**Issue by Poulern** [matthewbetts96/A3GearScriptGenerator#3]
In faction select screen I suggest Unit is associated with to be change to:
Faction is associated with:
West
East
Independent

This actually causes the marker file to be named [wrong](http://i.imgur.com/aAAqwNo.png) which causes it not be #included in f_setLocalGroupMarkers.sqf 

Other thing i noticed is in insert clothes its not really clear what the input form is, i assumed array, but i was wrong. So you have to input each "uniform" once which is 1. time consuming and 2. you dont always have 1 uniform, 1 vest, 1 backpack, 1 helmet, 1 glasses for each input. Clarify or make a check for what the input form is. Or make it do a "" between each ,

**Comment by matthewbetts96** [comment]
The Independent name fix is easy enough, just a few words. 

On the topic of the gear inputs, the program is built in such a way that only if a field has some characters in it will it be entered into the database. So you can leave fields blank and it won't affect the output.

	_uniform = uniformEntry.get()

	_vests = vestEntry.get()

	_backpacks = backpackEntry.get()

	_helmets = helmetEntry.get()

	_glasses = glassesEntry.get()

	_enablePopups = enablePopups.get()

	if(_uniform != ""):

		cur.execute('INSERT INTO uniforms(uniform,gearSide) VALUES (?,?)', (str(_uniform),str(unit_side)))

		sql.commit()

	if(_vests != ""):

		cur.execute('INSERT INTO vests(vest,gearSide) VALUES (?,?)', (str(_vests),str(unit_side)))

		sql.commit()

	if(_backpacks != ""):

		cur.execute('INSERT INTO backpacks(backpack,gearSide) VALUES (?,?)', (str(_backpacks),str(unit_side))),

		sql.commit()   

	if(_helmets != ""):

		cur.execute('INSERT INTO helmets(helmet,gearSide) VALUES (?,?)', (str(_helmets),str(unit_side)))

		sql.commit()

	if(_glasses != ""):

		cur.execute('INSERT INTO glasses(glasses,gearSide) VALUES (?,?)', (str(_glasses),str(unit_side)))

		sql.commit()

	if(_enablePopups == True):

		messagebox.showinfo("Notice", "Gear Inserted Successfully!")

However, I do agree that it needs to be explained better.
