### ISSUE TITLE
All typesofunit("m","r","ftl") must be lowercase

### ISSUE THREAD

**Issue by Poulern** [matthewbetts96/A3GearScriptGenerator#6]
the code does _typeofUnit = toLower (_this select 0); which means if case "AR": { arsenal code } then it will never call "AR" because in reality it calls "ar". 
However your program does not change the typeofunit to lowercase. 
Fix is NOT to change toLower (_this select 0); to _this select 0 as it will cause issues down the line.

**Comment by matthewbetts96** [comment]
Issue fixed with [this](https://github.com/matthewbetts96/A3GearScriptGenerator/commit/a08ed7b54e5c5e792c5a9fdf17794c61114f3734) update
